[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Variável de ambiente para indicar ao Next.js que estamos no ambiente Netlify
  NETLIFY_BUILD = "true"
  # Atualizar para Node 20
  NODE_VERSION = "20"

# Configuração para Deploy Previews
[context.deploy-preview]
  command = "npm run build"

# Configuração para Branch Deploys
[context.branch-deploy]
  command = "npm run build"

# Habilitar compartilhamento de Previews com senhas
[context.deploy-preview.environment]
  NETLIFY_PREVIEW_PASSWORD = "crypto"
  # Mantenha as mesmas variáveis de ambiente que em produção
  NETLIFY_BUILD = "true"
  
# Configuração para o Sanity Preview
[dev]
  command = "npm run dev"
  port = 3000
  autoLaunch = false
  framework = "nextjs"