# Configuração dos agentes do Blog Crew
# Este arquivo define as configurações para cada agente

monitor:
  name: Monitor
  description: "Agente que monitora feeds RSS e seleciona artigos relevantes para tradução"
  allow_delegation: false
  verbose: true
  temperature: 0.7
  max_iterations: 5

translator:
  name: Tradutor
  description: "Agente que traduz artigos selecionados para português brasileiro"
  allow_delegation: false
  verbose: true
  temperature: 0.5
  max_iterations: 3

formatter:
  name: Formatador
  description: "Agente que formata artigos traduzidos para publicação no Sanity CMS"
  allow_delegation: false
  verbose: true
  temperature: 0.3
  max_iterations: 3

publisher:
  name: Publicador
  description: "Agente que publica artigos formatados no Sanity CMS"
  allow_delegation: false
  verbose: true
  temperature: 0.2
  max_iterations: 2